// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'source.dart';
import 'value.dart';

// These functions are ignored because they are not marked as `pub`: `build_loaders`, `result_from_promise`, `result_from_sync`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsAsyncContext>>
abstract class JsAsyncContext implements RustOpaqueInterface {
  /// Evaluates JavaScript code.
  Future<JsResult> eval({required String code});

  /// Evaluates JavaScript code from a file.
  Future<JsResult> evalFile({required String path});

  /// Evaluates JavaScript code from a file with options.
  Future<JsResult> evalFileWithOptions(
      {required String path, required JsEvalOptions options});

  /// Evaluates a function from a module.
  Future<JsResult> evalFunction(
      {required String module, required String method, List<JsValue>? params});

  /// Evaluates JavaScript code with options.
  Future<JsResult> evalWithOptions(
      {required String code, required JsEvalOptions options});

  /// Creates a new async context from a runtime.
  static Future<JsAsyncContext> from({required JsAsyncRuntime rt}) =>
      LibFjs.instance.api.crateApiRuntimeJsAsyncContextFrom(rt: rt);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsAsyncRuntime>>
abstract class JsAsyncRuntime implements RustOpaqueInterface {
  /// Executes a pending job.
  Future<bool> executePendingJob();

  /// Puts the runtime into idle state.
  Future<void> idle();

  /// Checks if there are pending jobs.
  Future<bool> isJobPending();

  /// Returns memory usage statistics.
  Future<MemoryUsage> memoryUsage();

  /// Creates a new async runtime with default configuration.
  factory JsAsyncRuntime() =>
      LibFjs.instance.api.crateApiRuntimeJsAsyncRuntimeNew();

  /// Forces garbage collection.
  Future<void> runGc();

  /// Sets the garbage collection threshold.
  Future<void> setGcThreshold({required BigInt threshold});

  /// Sets runtime info string.
  Future<void> setInfo({required String info});

  /// Sets the maximum stack size.
  Future<void> setMaxStackSize({required BigInt limit});

  /// Sets the memory limit.
  Future<void> setMemoryLimit({required BigInt limit});

  /// Creates a new async runtime with custom configuration.
  static Future<JsAsyncRuntime> withOptions(
          {JsBuiltinOptions? builtin, List<JsModule>? additional}) =>
      LibFjs.instance.api.crateApiRuntimeJsAsyncRuntimeWithOptions(
          builtin: builtin, additional: additional);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsContext>>
abstract class JsContext implements RustOpaqueInterface {
  /// Evaluates JavaScript code.
  JsResult eval({required String code});

  /// Evaluates JavaScript code from a file.
  JsResult evalFile({required String path});

  /// Evaluates JavaScript code from a file with options.
  JsResult evalFileWithOptions(
      {required String path, required JsEvalOptions options});

  /// Evaluates JavaScript code with options.
  JsResult evalWithOptions(
      {required String code, required JsEvalOptions options});

  /// Creates a new context from a runtime.
  factory JsContext({required JsRuntime rt}) =>
      LibFjs.instance.api.crateApiRuntimeJsContextNew(rt: rt);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsRuntime>>
abstract class JsRuntime implements RustOpaqueInterface {
  /// Executes a pending job.
  bool executePendingJob();

  /// Checks if there are pending jobs.
  bool isJobPending();

  /// Returns memory usage statistics.
  MemoryUsage memoryUsage();

  /// Creates a new JavaScript runtime with default configuration.
  factory JsRuntime() => LibFjs.instance.api.crateApiRuntimeJsRuntimeNew();

  /// Forces garbage collection.
  void runGc();

  /// Sets dump flags for debugging.
  void setDumpFlags({required BigInt flags});

  /// Sets the garbage collection threshold.
  void setGcThreshold({required BigInt threshold});

  /// Sets runtime info string.
  void setInfo({required String info});

  /// Sets the maximum stack size.
  void setMaxStackSize({required BigInt limit});

  /// Sets the memory limit for the runtime.
  void setMemoryLimit({required BigInt limit});

  /// Creates a new JavaScript runtime with custom builtin modules.
  static Future<JsRuntime> withOptions(
          {JsBuiltinOptions? builtin, List<JsModule>? additional}) =>
      LibFjs.instance.api.crateApiRuntimeJsRuntimeWithOptions(
          builtin: builtin, additional: additional);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MemoryUsage>>
abstract class MemoryUsage implements RustOpaqueInterface {
  PlatformInt64 get arrayCount;

  PlatformInt64 get atomCount;

  PlatformInt64 get atomSize;

  PlatformInt64 get binaryObjectCount;

  PlatformInt64 get binaryObjectSize;

  PlatformInt64 get cFuncCount;

  PlatformInt64 get fastArrayCount;

  PlatformInt64 get fastArrayElements;

  PlatformInt64 get jsFuncCodeSize;

  PlatformInt64 get jsFuncCount;

  PlatformInt64 get jsFuncPc2LineCount;

  PlatformInt64 get jsFuncPc2LineSize;

  PlatformInt64 get jsFuncSize;

  PlatformInt64 get mallocCount;

  PlatformInt64 get mallocLimit;

  PlatformInt64 get mallocSize;

  PlatformInt64 get memoryUsedCount;

  PlatformInt64 get memoryUsedSize;

  PlatformInt64 get objCount;

  PlatformInt64 get objSize;

  PlatformInt64 get propCount;

  PlatformInt64 get propSize;

  PlatformInt64 get shapeCount;

  PlatformInt64 get shapeSize;

  PlatformInt64 get strCount;

  PlatformInt64 get strSize;

  /// Returns a human-readable summary of memory usage.
  String summary();

  /// Returns total allocation count.
  PlatformInt64 get totalAllocations;

  /// Returns total memory used in bytes.
  PlatformInt64 get totalMemory;
}
