#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT_DIR"

export PATH="$HOME/.cargo/bin:$PATH"

EXPECTED_VERSION="$(sed -En 's|^// @generated by `flutter_rust_bridge`@ ([0-9]+\.[0-9]+\.[0-9]+)\.$|\1|p' lib/src/frb/frb_generated.dart | head -n 1)"
if [ -z "$EXPECTED_VERSION" ]; then
  echo "error: unable to derive FRB codegen version from lib/src/frb/frb_generated.dart" >&2
  exit 1
fi

EXPECTED_OUTPUT="flutter_rust_bridge_codegen $EXPECTED_VERSION"
ACTUAL_OUTPUT="$(flutter_rust_bridge_codegen --version)"
if [ "$ACTUAL_OUTPUT" != "$EXPECTED_OUTPUT" ]; then
  echo "error: FRB codegen version mismatch: expected '$EXPECTED_OUTPUT', found '$ACTUAL_OUTPUT'" >&2
  exit 1
fi

RUSTUP_TOOLCHAIN=nightly flutter_rust_bridge_codegen generate
RUSTUP_TOOLCHAIN=nightly cargo fmt --manifest-path libfjs/Cargo.toml

if ! git diff --exit-code -- lib/src/frb libfjs/src/frb_generated.rs; then
  echo "error: FRB regeneration changed committed generated files" >&2
  exit 1
fi

echo "FRB generated files are reproducible with codegen $EXPECTED_VERSION."
