#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT_DIR"

export PATH="$HOME/.cargo/bin:$PATH"

if ! git diff HEAD --quiet --; then
  echo "error: FRB release provenance requires a clean tracked worktree" >&2
  exit 1
fi

EXPECTED_VERSION="$(sed -En 's|^// @generated by `flutter_rust_bridge`@ ([0-9]+\.[0-9]+\.[0-9]+)\.$|\1|p' lib/src/frb/frb_generated.dart | head -n 1)"
if [ -z "$EXPECTED_VERSION" ]; then
  echo "error: unable to derive FRB codegen version from lib/src/frb/frb_generated.dart" >&2
  exit 1
fi

EXPECTED_OUTPUT="flutter_rust_bridge_codegen $EXPECTED_VERSION"
ACTUAL_OUTPUT="$(flutter_rust_bridge_codegen --version)"
if [ "$ACTUAL_OUTPUT" != "$EXPECTED_OUTPUT" ]; then
  echo "error: FRB codegen version mismatch: expected '$EXPECTED_OUTPUT', found '$ACTUAL_OUTPUT'" >&2
  exit 1
fi

# Generated files are formatted with nightly so regeneration is
# reproducible; CI installs the same toolchain.
FRB_FMT_TOOLCHAIN=nightly

# Expansion output differs between cargo-expand releases (it re-prints the
# expanded code with its bundled formatter), which shifts the generated
# trait-ignore headers. Require the pinned release; otherwise FRB silently
# auto-installs the latest one. build-all-platforms.yml installs the same pin.
FRB_CARGO_EXPAND_VERSION=1.0.126
ACTUAL_CARGO_EXPAND="$(cargo expand --version 2>/dev/null || true)"
if [ "$ACTUAL_CARGO_EXPAND" != "cargo-expand $FRB_CARGO_EXPAND_VERSION" ]; then
  echo "error: cargo-expand $FRB_CARGO_EXPAND_VERSION is required for reproducible regeneration, found '$ACTUAL_CARGO_EXPAND'" >&2
  echo "       install it with: cargo install cargo-expand --version $FRB_CARGO_EXPAND_VERSION --locked" >&2
  exit 1
fi

RUSTUP_TOOLCHAIN=$FRB_FMT_TOOLCHAIN flutter_rust_bridge_codegen generate
RUSTUP_TOOLCHAIN=$FRB_FMT_TOOLCHAIN cargo fmt --manifest-path libfjs/Cargo.toml

if ! git diff --exit-code -- lib/src/frb libfjs/src/frb_generated.rs; then
  echo "error: FRB regeneration changed committed generated files" >&2
  exit 1
fi

if ! git diff HEAD --exit-code --; then
  echo "error: FRB regeneration or Rust formatting changed committed tracked files" >&2
  exit 1
fi

echo "FRB generated files are reproducible with codegen $EXPECTED_VERSION."
